export const categories = [
  {
    id: 'historical',
    name: 'Historical & Cultural Sites',
    emoji: '🏛️',
    description: 'Museums, monuments, heritage sites, and cultural landmarks',
    color: 'from-amber-500 to-orange-600',
    icon: '🏛️',
    screens: [
      'historical-timeline',
      'historical-events',
      'cultural-events',
      'guided-tours',
      'archaeology',
      'heritage-preservation',
      'historical-figures',
      'restoration-projects',
      'historical-documents',
      'virtual-tours',
      'educational-programs',
      'historical-photos',
      'historical-maps',
      'artifact-collections',
      'historical-reenactments',
      'cultural-workshops',
      'historical-architecture',
      'historical-research',
      'historical-news'
    ]
  },
  {
    id: 'nature',
    name: 'Parks & Nature',
    emoji: '🌳',
    description: 'National parks, gardens, wildlife reserves, and natural attractions',
    color: 'from-green-500 to-emerald-600',
    icon: '🌳',
    screens: [
      'nature-trails',
      'wildlife-spotting',
      'conservation-efforts',
      'botanical-collections',
      'nature-photography',
      'bird-watching',
      'nature-education',
      'eco-tours',
      'camping-sites',
      'hiking-routes',
      'nature-calendar',
      'volunteer-programs',
      'nature-research',
      'geological-features',
      'waterfalls',
      'nature-webcams',
      'nature-sounds',
      'seasonal-highlights',
      'nature-news'
    ]
  },
  {
    id: 'beaches',
    name: 'Beaches & Waterfronts',
    emoji: '🏖️',
    description: 'Coastal areas, beaches, lakes, and waterfront attractions',
    color: 'from-blue-500 to-cyan-600',
    icon: '🏖️',
    screens: [
      'beach-conditions',
      'water-sports',
      'tide-tables',
      'beach-safety',
      'marine-life',
      'beach-cams',
      'beach-amenities',
      'beach-cleanups',
      'sunset-spots',
      'beach-events',
      'beach-accessibility',
      'beach-photography',
      'beach-volleyball',
      'beach-restaurants',
      'beach-rentals',
      'beach-rules',
      'beach-weather',
      'beach-news'
    ]
  },
  {
    id: 'mountains',
    name: 'Mountains & Adventure',
    emoji: '🏔️',
    description: 'Mountain ranges, hiking trails, and adventure sports',
    color: 'from-slate-500 to-gray-600',
    icon: '🏔️',
    screens: [
      'mountain-trails',
      'climbing-routes',
      'adventure-sports',
      'mountain-conditions',
      'ski-resorts',
      'mountain-lodges',
      'altitude-info',
      'mountain-safety',
      'mountain-photography',
      'mountain-wildlife',
      'mountain-geology',
      'mountain-weather',
      'mountain-rescues',
      'mountain-events',
      'mountain-culture',
      'mountain-history',
      'mountain-transport',
      'mountain-news'
    ]
  },
  {
    id: 'theme-parks',
    name: 'Theme & Amusement Parks',
    emoji: '🎡',
    description: 'Amusement parks, theme parks, and entertainment venues',
    color: 'from-pink-500 to-rose-600',
    icon: '🎡',
    screens: [
      'rides-attractions',
      'park-map',
      'wait-times',
      'park-events',
      'character-meetups',
      'dining-options',
      'height-requirements',
      'fastpass-info',
      'park-hours',
      'ticket-prices',
      'parking-info',
      'hotels-resorts',
      'special-tours',
      'seasonal-decorations',
      'souvenir-shops',
      'park-safety',
      'park-history',
      'park-news'
    ]
  },
  {
    id: 'arts',
    name: 'Arts & Entertainment',
    emoji: '🎭',
    description: 'Theaters, galleries, concert halls, and cultural venues',
    color: 'from-purple-500 to-violet-600',
    icon: '🎭',
    screens: [
      'current-exhibitions',
      'upcoming-events',
      'artist-spotlights',
      'art-collections',
      'performance-schedule',
      'ticket-booking',
      'art-workshops',
      'artist-residencies',
      'art-history',
      'art-auctions',
      'art-restoration',
      'art-education',
      'art-technology',
      'art-philanthropy',
      'art-publications',
      'art-news'
    ]
  },
  {
    id: 'shopping',
    name: 'Shopping & Markets',
    emoji: '🛍️',
    description: 'Markets, shopping centers, and retail destinations',
    color: 'from-indigo-500 to-blue-600',
    icon: '🛍️',
    screens: [
      'store-directory',
      'sales-promotions',
      'market-stalls',
      'local-artisans',
      'shopping-events',
      'gift-guides',
      'shopping-tours',
      'luxury-brands',
      'souvenir-shops',
      'boutique-stores',
      'shopping-tips',
      'shopping-history',
      'shopping-culture',
      'shopping-news'
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink Experiences',
    emoji: '🍇',
    description: 'Restaurants, food tours, wineries, and culinary experiences',
    color: 'from-red-500 to-pink-600',
    icon: '🍇',
    screens: [
      'restaurant-guide',
      'food-tours',
      'cooking-classes',
      'wine-tastings',
      'local-specialties',
      'chef-interviews',
      'food-festivals',
      'farmers-markets',
      'food-history',
      'food-safety',
      'dietary-options',
      'food-photography',
      'food-news'
    ]
  },
  {
    id: 'religious',
    name: 'Religious & Spiritual Sites',
    emoji: '🕌',
    description: 'Churches, temples, mosques, and spiritual destinations',
    color: 'from-yellow-500 to-amber-600',
    icon: '🕌',
    screens: [
      'worship-schedule',
      'religious-history',
      'pilgrimage-routes',
      'sacred-art',
      'religious-events',
      'spiritual-retreats',
      'meditation-guides',
      'religious-architecture',
      'religious-texts',
      'interfaith-dialogue',
      'religious-tourism',
      'religious-news'
    ]
  },
  {
    id: 'adventure',
    name: 'Adventure & Outdoor Activities',
    emoji: '🚤',
    description: 'Water sports, extreme sports, and outdoor adventures',
    color: 'from-teal-500 to-green-600',
    icon: '🚤',
    screens: [
      'activity-listings',
      'equipment-rentals',
      'safety-guidelines',
      'instructor-profiles',
      'adventure-packages',
      'extreme-sports',
      'family-activities',
      'adventure-blog',
      'adventure-photography',
      'adventure-news'
    ]
  }
];
